### ISSUE TITLE
Slack Channel Invitation

### ISSUE THREAD

**Issue by pomonam** [alecjacobson/geometryprocessingcoursepage#1]
Hello Everyone,

Can we use this issue thread to ask one of gdp members to invite us on slack?

My email address is as follows.
juhan.bae [at] mail.utoronto.ca

Thank you very much!

**Comment by RuijianSZ** [comment]
Can anybody invite me too? My email is ruijian.an@mail.utoronto.ca. Thanks!

**Comment by songfeil** [comment]
Hi, can anyone invite me to the channel? Email is feilong.song@mail.utoronto.ca. Thanks a lot in advance!

**Comment by cuppajoeman** [comment]
May I join? callum.cassidynolan@mail.utoronto.ca
